### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by adud** [ens-lyon-2017/compass2018#11]
Faire un tableau de benchmark pour chaque test et chaque amélioration

**Comment by adud** [comment]
Avec coût de bits et taille du code

**Comment by fdedinec** [comment]
Le tableau est dans le latex... Yapuka le remplir.

**Comment by adud** [comment]
Le problème est qu'on n'aura pas le temps de faire une ISA avec les nouvelles opérations… C'est dommage, j'avais une version de la multiplication matricielle avec un gain de presque un tiers quant à la taille du code. 
Au-delà de Compass, il faut absolument ajouter des choses pour survivre au cours de compilo de l'an prochain.

**Comment by adud** [comment]
De même dans le tableau, met-on les optimisations des modes d'adressage mémoire ? D'ailleurs on a un trou sur ce point… @fdedinec

**Comment by fdedinec** [comment]
pas compris la question.

**Comment by fdedinec** [comment]
J'ai un souci, l'exécution des commandes suivantes donne plus de bits pour l'encodage de huffman?

./emu/emu -i prog/mult.bin | ./huffmann.py > mult.huff

# pour le .obj ou compter les bits
./asm.py --loadhuffman mult.huff --stdout  prog/mult.s > mult.obj.huff
# Puis éditer à la main pour compter les bits, argh.

#pour le .bin
./asm.py  prog/mult.s -b --loadhuffman mult.huff -o prog/mult.huff.bin 
./emu/emu -s -lh mult.huff -i prog/mult.huff.bin

# Et maintenant la comparaison 
./emu/emu -s  -i prog/mult.bin

**Comment by adud** [comment]
hardcoder c'est le mal, les dieux de l'Informatique nous ont bien puni
