### ISSUE TITLE
Huffman tree Python

### ISSUE THREAD

**Issue by icannos** [ens-lyon-2017/compass2018#9]
Il faudrait que quelqu'un se charge de reprendre en python le générateur d'arbre de huffman à partir des statistiques de @Cemoixerestre (Ce serait cool que tu puisses ajouter à ce fil le format de tes stats)
Et en gardant à l'esprit qu'il faut la sortie suivante (pour pouvoir la charger dans l'émulateur à l'exécution):

Une première ligne avec le taille du plus long opcode de l'encodage généré. Puis une ligne par instruction  (exactement 37 instructions). Sur chaque ligne dans cet ordre et séparé par un espace: 
`mnemonic` `id interne` `taille de l'opcode` `opcode`. (Désolé pour ces airs d'UVA)
```
5
add2i 0 5 11111 
```

Une fois cela fait il faudra aussi adapter l'asm.py afin d'assembler à partir de l'arbre.

**Comment by Cemoixerestre** [comment]
C'est fait ! Tout est dans le fichier `asm2017/huffman.py`. Si ça te convient, je peux fermer l'issue.

**Comment by icannos** [comment]
Cool ! Il ne reste plus qu'à assemblé à partir de ce nouvel encodage mais ça c'est pas bien compliqué: il y a un dico dans asm.py je crois qui recense les associations mnemonics / opcode. Il suffit de le remplir en lisant ce que tu viens de nous faire !

**Comment by Cemoixerestre** [comment]
Je viens d'essayer de lancer mon programme sur des statistiques issues du programme de multiplication de matrices par Antonin.

Données en entrée : 

    0 add2 217
    1 add2i 29
    2 sub2 24
    3 sub2i 95
    4 cmp 0
    5 cmpi 227
    6 let 6
    7 leti 27
    8 shift 458
    9 readze 338
    10 readse 0
    11 jump 1
    12 jumpif 544
    13 or2 0
    14 or2i 0
    15 and2 0
    16 and2i 0
    17 write 16
    18 call 75
    19 setctr 115
    20 getctr 89
    21 push 210
    22 return 75
    23 add3 0
    24 add3i 0
    25 sub3 0
    26 sub3i 0
    27 and3 0
    28 and3i 0
    29 or3 0
    30 or3i 0
    31 xor3 0
    32 xor3i 0
    33 asr3 0
    34 sleep 0
    35 rand 0
    36 (res) 0

Sortie : 
    29
    add2 0 4 0010
    add2i 1 7 0001100
    sub2 2 7 0001110
    sub2i 3 5 01100
    cmp 4 11 00011111110
    cmpi 5 4 0000
    let 6 9 000111110
    leti 7 7 0001101
    shift 8 2 11
    readze 9 3 010
    readse 10 12 000111111110
    jump 11 10 0001111110
    jumpif 12 2 10
    or2 13 13 0001111111110
    or2i 14 14 00011111111110
    and2 15 15 000111111111110
    and2i 16 16 0001111111111110
    write 17 8 00011110
    call 18 5 01110
    setctr 19 5 00010
    getctr 20 5 01101
    push 21 4 0011
    return 22 5 01111
    add3 23 17 00011111111111110
    add3i 24 18 000111111111111110
    sub3 25 19 0001111111111111110
    sub3i 26 20 00011111111111111110
    and3 27 21 000111111111111111110
    and3i 28 22 0001111111111111111110
    or3 29 23 00011111111111111111110
    or3i 30 24 000111111111111111111110
    xor3 31 25 0001111111111111111111110
    xor3i 32 26 00011111111111111111111110
    asr3 33 27 000111111111111111111111110
    sleep 34 28 0001111111111111111111111110
    rand 35 29 00011111111111111111111111110
    (res) 36 29 00011111111111111111111111111

Le problème est que comme beaucoup d'instructions ne sont jamais exécutées, leurs codes de Huffmann peuvent être absurdement longs. Il pourrait être utile de rajouter donc un poids bidon à toutes les instructions (par exemple 1) pour éviter d'avoir des instructions de poids 0 et donc des codages aussi déséquilibrés.

**Comment by icannos** [comment]
Si on leur donne un poids, certes elles coûteront moins chères mais elles pénaliseront toutes les autres.
Je pense que supprimer purement et simplement ces instructions serait mieux. (Ou seulement les ignorer puisque de toutes façons on ne les utilise pas).

Cela peut d'ailleurs constituer un point du papier concernant les opérations qui peuvent être supprimées si l'on souhaitait construire un proco plus simple.

**Comment by lephe** [comment]
Le truc c'est que la table qui me permet d'accélérer le décodage des instructions ne marchera jamais au-delà de 15/16 bits (après ça devient du gaspillage). On peut s'y prendre de plusieurs manières, éventuellement :

- Modifier le Huffman pour que les instructions inutilisées se trouvent avec un pattern `11...11xx..xx` où les `x` sont un codage binaire normal, au lieu de continuer sur le Huffmann ;
- Adapter violemment la table de décodage pour supporter des "trous" dans le jeu d'instructions (honnêtement, ce serait une galère).

J'attends de voir ce qu'on peut obtenir comme longueur (16 à vue de nez, sur l'échantillon précédent), si besoin je réécrirai la partie concernée.

Dans tous les cas, si dans votre jeu de données « maître » il y a des instructions inutilisées, il faut peut-être vous poser quelques questions.

**Comment by Cemoixerestre** [comment]
J'ai fait en sorte que le sous-arbre qui possède les éléments de poids nul soit équilibré. Ça résout notre problème pour cet exemple là, les intsructions font moins de 15 caractères.

Résultat : 

    15
    add2 0 4 0010
    add2i 1 7 0001100
    sub2 2 7 0001110
    sub2i 3 5 01100
    cmp 4 14 00011111110000
    cmpi 5 4 0000
    let 6 9 000111110
    leti 7 7 0001101
    shift 8 2 11
    readze 9 3 010
    readse 10 14 00011111110001
    jump 11 10 0001111110
    jumpif 12 2 10
    or2 13 14 00011111110010
    or2i 14 15 000111111100110
    and2 15 15 000111111100111
    and2i 16 14 00011111110100
    write 17 8 00011110
    call 18 5 01110
    setctr 19 5 00010
    getctr 20 5 01101
    push 21 4 0011
    return 22 5 01111
    add3 23 14 00011111110101
    add3i 24 14 00011111110110
    sub3 25 15 000111111101110
    sub3i 26 15 000111111101111
    and3 27 14 00011111111000
    and3i 28 14 00011111111001
    or3 29 14 00011111111010
    or3i 30 15 000111111110110
    xor3 31 15 000111111110111
    xor3i 32 14 00011111111100
    asr3 33 14 00011111111101
    sleep 34 14 00011111111110
    rand 35 15 000111111111110
    (res) 36 15 000111111111111

P.S : J'ai essayé de faire des branches… et j'ai fait un peu nimporte quoi. Je corrige mes erreurs au plus vite.

**Comment by lephe** [comment]
Parfait ! Entre ça et le chargement dynamique, tout est prêt pour faire les stats comparatives.

**Comment by icannos** [comment]
Je viens d'ajouter l'option pour demander à l'asm.py d'assembler selon un codage de huffman généré par @Cemoixerestre ;)

**Comment by Cemoixerestre** [comment]
Est-ce que tu as testé ? Il me semble que le codage de Huffman n'est a priori pas compatible avec des instructions comme `jump` ou `jumpif`.

**Comment by icannos** [comment]
Je n'ai pas eu encore le temps de tester l'exécution avec l'émulateur en revanche le le truc sort un fichier binaire qui semble correct. J'empile ça.

**Comment by lephe** [comment]
J'ai bien fait de l'annoter, ça. `jump` et `jumpif` utilisent l'adresse de l'instruction pour tester les sauts de taille nulle. Quand j'ai écrit l'émulateur, j'ai hardcodé le nombre de bits de ces instructions dans les procédures associées.

J'ai implémenté une solution (pas testée live, par contre) et push sur le repo.

**Comment by adud** [comment]
Est-ce que c'est une bonne idée de faire ça sur la multiplication matricielle ? C'est quand même quelque chose d'extrêmement spécifique, peut-être vaudrait-il mieux faire des stats sur `TETRIS`, par exemple

**Comment by icannos** [comment]
Il faut en discuter avec Florent. On en a un peu parlé tout à l'heure. A voir vers 17h :p

**Comment by lephe** [comment]
Si @adud parle bien de la détection des halt loops... c'est un pure artifice de l'émulateur qui n'a strictement aucune influence au niveau du processeur, et qui ne change pas la sémantique du programme.

**Comment by adud** [comment]
Un Huffman Tree qui marche !
